// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeURL(arg1) {
  return window['go']['main']['App']['AnalyzeURL'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ChooseCookieFile() {
  return window['go']['main']['App']['ChooseCookieFile']();
}

export function ChooseOutputDirectory() {
  return window['go']['main']['App']['ChooseOutputDirectory']();
}

export function ClearFinishedDownloads() {
  return window['go']['main']['App']['ClearFinishedDownloads']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCookieBrowsers() {
  return window['go']['main']['App']['GetCookieBrowsers']();
}

export function GetDependencies() {
  return window['go']['main']['App']['GetDependencies']();
}

export function GetInstallGuidance() {
  return window['go']['main']['App']['GetInstallGuidance']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetToolSources() {
  return window['go']['main']['App']['GetToolSources']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function LocateDependency(arg1) {
  return window['go']['main']['App']['LocateDependency'](arg1);
}

export function OpenContainingFolder(arg1) {
  return window['go']['main']['App']['OpenContainingFolder'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function OpenOutputDirectory() {
  return window['go']['main']['App']['OpenOutputDirectory']();
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PreviewCommand(arg1) {
  return window['go']['main']['App']['PreviewCommand'](arg1);
}

export function RefreshDependencies() {
  return window['go']['main']['App']['RefreshDependencies']();
}

export function ResolveEntry(arg1) {
  return window['go']['main']['App']['ResolveEntry'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['main']['App']['SkipUpdateVersion'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}
