// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {downloads} from '../models';
import {dependencies} from '../models';
import {config} from '../models';

export function AnalyzeURL(arg1:main.AnalyzeRequest):Promise<main.AnalyzeResponse>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateStatus>;

export function ChooseCookieFile():Promise<string>;

export function ChooseOutputDirectory():Promise<string>;

export function ClearFinishedDownloads():Promise<Array<downloads.View>>;

export function DownloadUpdate():Promise<main.UpdateStatus>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetCookieBrowsers():Promise<Array<string>>;

export function GetDependencies():Promise<dependencies.Set>;

export function GetInstallGuidance():Promise<Array<dependencies.Guidance>>;

export function GetSettings():Promise<main.SettingsResponse>;

export function GetToolSources():Promise<Array<main.ToolSource>>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function InstallTool(arg1:string):Promise<main.ToolInstallResponse>;

export function InstallUpdate():Promise<void>;

export function ListDownloads():Promise<Array<downloads.View>>;

export function LocateDependency(arg1:string):Promise<main.SettingsResponse>;

export function OpenContainingFolder(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenLogDirectory():Promise<void>;

export function OpenOutputDirectory():Promise<void>;

export function OpenReleasePage():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PreviewCommand(arg1:main.DownloadRequest):Promise<main.PreviewResponse>;

export function RefreshDependencies():Promise<dependencies.Set>;

export function ResolveEntry(arg1:string):Promise<main.AnalyzeResponse>;

export function SaveSettings(arg1:config.Config):Promise<main.SettingsResponse>;

export function SkipUpdateVersion(arg1:string):Promise<main.UpdateStatus>;

export function StartDownload(arg1:main.DownloadRequest):Promise<main.StartResponse>;

export function UpdateTool(arg1:string):Promise<main.ToolInstallResponse>;
